# Generated by Django 2.1.5 on 2019-01-15 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Reap', 'REAP'), ('Fight', 'FIGHT'), ('Action', 'ACTION'), ('Play', 'PLAY')], max_length=6)),
                ('rank', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='card.Card')),
            ],
            options={
                'ordering': ('-rank',),
            },
        ),
        migrations.CreateModel(
            name='Synergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('cards', models.ManyToManyField(through='synergy.Event', to='card.Card')),
                ('synergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='synergy.Synergy')),
            ],
            options={
                'ordering': ('-rank',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='synergy.Turn'),
        ),
    ]
