# Generated by Django 2.1.5 on 2019-01-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-rank',)},
        ),
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ('-rank',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Reap', 'REAP'), ('Attack', 'ATTACK'), ('Action', 'ACTION'), ('Play', 'PLAY')], max_length=6),
        ),
    ]
