# Generated by Django 2.1.5 on 2019-01-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='synergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='synergy.Synergy'),
        ),
    ]
