# Generated by Django 2.1.5 on 2019-01-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0002_auto_20190111_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='card.Card'),
        ),
        migrations.AlterField(
            model_name='event',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='synergy.Turn'),
        ),
    ]
