# Generated by Django 2.1.5 on 2019-01-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('card_title', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('front_image', models.CharField(max_length=255)),
                ('card_text', models.CharField(max_length=255)),
                ('traits', models.CharField(max_length=255, null=True)),
                ('amber', models.IntegerField()),
                ('power', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('rarity', models.CharField(max_length=255)),
                ('flavor_text', models.CharField(max_length=255, null=True)),
                ('card_number', models.CharField(max_length=255)),
                ('expansion', models.CharField(max_length=255)),
            ],
        ),
    ]
