# Generated by Django 2.1.5 on 2019-01-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('rarity', models.CharField(max_length=255)),
                ('aember', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('armor', models.IntegerField(null=True)),
                ('traits', models.CharField(max_length=255, null=True)),
                ('keywords', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('imageurl', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255, null=True)),
                ('setsku', models.CharField(max_length=255)),
            ],
        ),
    ]
