# Generated by Django 2.1.5 on 2019-01-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20190111_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
